=== thristovska098/JSON-and-XML/XML, XML Schema and XSLT/education_centers.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:complexType name="address_type">
    <xs:sequence>
      <xs:element name="street" type="xs:string"/>
      <xs:element name="number" type="xs:nonNegativeInteger"/>
      <xs:element name="zip" type="xs:nonNegativeInteger"/>
      <xs:element name="city" type="xs:string"/>
      <xs:element name="country" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>
  <xs:simpleType name="platform_type">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Zoom"/>
      <xs:enumeration value="BBB"/>
      <xs:enumeration value="Google Teams"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="lessons_type" mixed="true">
    <xs:choice>
      <xs:element name="inperson">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="room_number" type="xs:nonNegativeInteger"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="online">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="platform" type="platform_type"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:choice>
  </xs:complexType>
  <xs:simpleType name="ssn_type">
    <xs:restriction base="xs:string">
      <xs:length value="13"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="phone_type">
    <xs:restriction base="xs:string">
      <xs:pattern value="[0-9]{3}/[0-9]{3}-[0-9]{3}"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:group name="person">
    <xs:sequence>
      <xs:element name="first_name" type="xs:string"/>
      <xs:element name="last_name" type="xs:string"/>
      <xs:element name="address" type="address_type"/>
      <xs:element name="birth_date" type="xs:date"/>
      <xs:element name="email" type="xs:string"/>
      <xs:element name="phone_number" type="phone_type"/>
    </xs:sequence>
  </xs:group>
  <xs:complexType name="candidate_type">
    <xs:sequence>
      <xs:group ref="person"/>
    </xs:sequence>
    <xs:attribute name="ssn_candidate" type="ssn_type" use="required"/>
  </xs:complexType>
  <xs:complexType name="candidates_type">
    <xs:sequence>
      <xs:element name="candidate" type="candidate_type" minOccurs="1" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
  <xs:simpleType name="education_type">
    <xs:restriction base="xs:string">
      <xs:enumeration value="certificate"/>
      <xs:enumeration value="doctoral"/>
      <xs:enumeration value="master"/>
      <xs:enumeration value="bachelor"/>
      <xs:enumeration value="associate degree"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="lecturer_type">
    <xs:sequence>
      <xs:group ref="person"/>
      <xs:element name="education" type="education_type"/>
    </xs:sequence>
    <xs:attribute name="ssn_lecturer" type="ssn_type" use="required"/>
  </xs:complexType>
  <xs:complexType name="lecturers_type">
    <xs:sequence>
      <xs:element name="lecturer" type="lecturer_type" minOccurs="1" maxOccurs="50"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="candidate_group_type">
    <xs:attribute name="ssn_candidate" type="ssn_type" use="required"/>
  </xs:complexType>
  <xs:complexType name="location_type">
    <xs:sequence>
      <xs:element name="address" type="address_type"/>
      <xs:element name="capacity" type="xs:nonNegativeInteger"/>
      <xs:element name="lesson_type" type="lessons_type"/>
    </xs:sequence>
    <xs:attribute name="location_id" type="xs:nonNegativeInteger" use="required"/>
  </xs:complexType>
  <xs:complexType name="group_type">
    <xs:sequence>
      <xs:element name="candidate_belongs_to_group" type="candidate_group_type"/>
    </xs:sequence>
    <xs:attribute name="id_group" type="xs:nonNegativeInteger" use="required"/>
  </xs:complexType>
  <xs:complexType name="groups_type">
    <xs:sequence>
      <xs:element type="group_type" name="group" minOccurs="0" maxOccurs="10"/>
    </xs:sequence>
  </xs:complexType>
  <xs:simpleType name="type_program_type">
    <xs:restriction base="xs:string">
      <xs:enumeration value="course"/>
      <xs:enumeration value="academy"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="code_type">
    <xs:restriction base="xs:string">
      <xs:length value="7"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="education_program_type">
    <xs:sequence>
      <xs:element name="name_program" type="xs:string"/>
      <xs:element name="type_program" type="type_program_type"/>
      <xs:element name="description" type="xs:string"/>
      <xs:element name="total_lectures" type="xs:nonNegativeInteger"/>
      <xs:element name="program_price" type="xs:nonNegativeInteger"/>
      <xs:element name="start_date" type="xs:date"/>
      <xs:element name="groups" type="groups_type"/>
    </xs:sequence>
    <xs:attribute name="code_program" type="code_type" use="required"/>
  </xs:complexType>
  <xs:complexType name="education_programs_type">
    <xs:sequence>
      <xs:element name="education_program" type="education_program_type" minOccurs="1" maxOccurs="15"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="lecturer_teach_lecture_type">
    <xs:attribute name="ssn_lecturer" type="ssn_type" use="required"/>
  </xs:complexType>
  <xs:simpleType name="code_lecture_type">
    <xs:restriction base="xs:string">
      <xs:length value="9"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="duration_hours_type">
    <xs:restriction base="xs:nonNegativeInteger">
      <xs:enumeration value="1"/>
      <xs:enumeration value="2"/>
      <xs:enumeration value="3"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="lecture_type">
    <xs:sequence>
      <xs:element name="lecture_number" type="xs:nonNegativeInteger"/>
      <xs:element name="on_date" type="xs:date"/>
      <xs:element name="start_hour" type="xs:time"/>
      <xs:element name="duration_hours" type="duration_hours_type"/>
      <xs:element name="location" type="location_type"/>
      <xs:element name="lecturer_teach_lecture" type="lecturer_teach_lecture_type"/>
    </xs:sequence>
    <xs:attribute name="code_lecture" type="code_lecture_type"/>
  </xs:complexType>
  <xs:complexType name="schedule_type">
    <xs:sequence>
      <xs:element name="from_date" type="xs:date"/>
      <xs:element name="to_date" type="xs:date"/>
      <xs:element name="lectures">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="lecture" type="lecture_type" minOccurs="1" maxOccurs="50"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute type="xs:integer" name="id_schedule" use="required"/>
  </xs:complexType>
  <xs:complexType name="schedules_type">
    <xs:sequence>
      <xs:element name="schedule" type="schedule_type" minOccurs="1" maxOccurs="5"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="education_center_type">
    <xs:sequence>
      <xs:element name="name_of_center" type="xs:string"/>
      <xs:element name="education_programs" type="education_programs_type"/>
      <xs:element name="lecturers" type="lecturers_type"/>
      <xs:element name="candidates" type="candidates_type"/>
      <xs:element name="schedules" type="schedules_type"/>
    </xs:sequence>
  </xs:complexType>
  <xs:element name="education_centers">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="education_center" type="education_center_type" minOccurs="1" maxOccurs="50"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== thristovska098/JSON-and-XML/XML, XML Schema and XSLT/education_centers.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="education_centers.xsl"?>
<education_centers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///C:/Users/Teodora/Desktop/Documents/XmlPad%20Projects/education_centers.xsd">
  <education_center>
    <name_of_center>Centar za edukacija A</name_of_center>
    <education_programs>
      <education_program code_program="CS00000">
        <name_program>Java Full Stack</name_program>
        <type_program>academy</type_program>
        <description>The full stack developer definition is “someone who can work on both the back-end and front-end of systems.” This means that they can develop fully fledged platforms (with databases, servers and clients) which don’t need other applications to function.</description>
        <total_lectures>300</total_lectures>
        <program_price>30000</program_price>
        <!-- cenata e vo denari -->
        <start_date>2021-01-15</start_date>
        <groups>
          <group id_group="1">
            <candidate_belongs_to_group ssn_candidate="0000123456789"/>
          </group>
        </groups>
      </education_program>
      <education_program code_program="CS00001">
        <name_program>JDBC</name_program>
        <type_program>course</type_program>
        <description>JDBC stands for Java Database Connectivity and provides a basic API to connect a database and read/write data. You can execute SQL queries, call stored procedures, and parse ResultSet to create Java objects.</description>
        <total_lectures>150</total_lectures>
        <program_price>15000</program_price>
        <!-- cenata e vo denari -->
        <start_date>2021-01-15</start_date>
        <groups>
          <group id_group="2">
            <candidate_belongs_to_group ssn_candidate="0000123456789"/>
          </group>
        </groups>
      </education_program>
    </education_programs>
    <lecturers>
      <lecturer ssn_lecturer="1234567890000">
        <first_name>Jadranka</first_name>
        <last_name>Jadranovska</last_name>
        <address>
          <street>Ulica</street>
          <number>11</number>
          <zip>8000</zip>
          <city>Grad</city>
          <country>Drzava</country>
        </address>
        <birth_date>1970-10-10</birth_date>
        <email>nekojemail@yahoo.com</email>
        <phone_number>075/555-999</phone_number>
        <education>bachelor</education>
      </lecturer>
      <lecturer ssn_lecturer="1234567890011">
        <first_name>Tome</first_name>
        <last_name>Tomevski</last_name>
        <address>
          <street>Ulica</street>
          <number>15</number>
          <zip>6000</zip>
          <city>Grad</city>
          <country>Drzava</country>
        </address>
        <birth_date>1975-11-10</birth_date>
        <email>nekojemail11@yahoo.com</email>
        <phone_number>075/666-999</phone_number>
        <education>doctoral</education>
      </lecturer>
      <lecturer ssn_lecturer="1234567890011">
        <first_name>Ana</first_name>
        <last_name>Anovska</last_name>
        <address>
          <street>Ulica</street>
          <number>10</number>
          <zip>7000</zip>
          <city>Bitola</city>
          <country>Drzava</country>
        </address>
        <birth_date>1975-11-10</birth_date>
        <email>nekojemail11@yahoo.com</email>
        <phone_number>075/666-999</phone_number>
        <education>doctoral</education>
      </lecturer>
    </lecturers>
    <candidates>
      <candidate ssn_candidate="0000123456789">
        <first_name>Filip</first_name>
        <last_name>Filipovski</last_name>
        <address>
          <street>Nekoja ulica</street>
          <number>11</number>
          <zip>7000</zip>
          <city>Bitola</city>
          <country>Drzava</country>
        </address>
        <birth_date>1970-10-10</birth_date>
        <email>nekojemail@yahoo.com</email>
        <phone_number>075/555-999</phone_number>
      </candidate>
      <candidate ssn_candidate="0000123456789">
        <first_name>Petranka</first_name>
        <last_name>Petranovsk</last_name>
        <address>
          <street>Nekoja ulica</street>
          <number>11</number>
          <zip>0000</zip>
          <city>Prilep</city>
          <country>Drzava</country>
        </address>
        <birth_date>1970-10-10</birth_date>
        <email>nekojemail@yahoo.com</email>
        <phone_number>075/555-999</phone_number>
      </candidate>
    </candidates>
    <schedules>
      <schedule id_schedule="1">
        <from_date>2020-12-06</from_date>
        <to_date>2021-05-05</to_date>
        <lectures>
          <lecture code_lecture="AB1234567">
            <lecture_number>1</lecture_number>
            <on_date>2020-12-01</on_date>
            <start_hour>15:00:00</start_hour>
            <duration_hours>1</duration_hours>
            <location location_id="1">
              <address>
                <street>Nekoja ulica</street>
                <number>11</number>
                <zip>8000</zip>
                <city>Grad</city>
                <country>Drzava</country>
              </address>
              <capacity>20</capacity>
              <lesson_type>
                <online>
                  <platform>Zoom</platform>
                </online>
              </lesson_type>
            </location>
            <lecturer_teach_lecture ssn_lecturer="1234567890000"/>
          </lecture>
          <lecture code_lecture="AB1234566">
            <lecture_number>5</lecture_number>
            <on_date>2020-12-01</on_date>
            <start_hour>15:00:00</start_hour>
            <duration_hours>2</duration_hours>
            <location location_id="1">
              <address>
                <street>Nekoja ulica</street>
                <number>11</number>
                <zip>8000</zip>
                <city>Grad</city>
                <country>Drzava</country>
              </address>
              <capacity>20</capacity>
              <lesson_type>
                <online>
                  <platform>Zoom</platform>
                </online>
              </lesson_type>
            </location>
            <lecturer_teach_lecture ssn_lecturer="1234567890000"/>
          </lecture>
          <lecture code_lecture="AB1234555">
            <lecture_number>3</lecture_number>
            <on_date>2020-12-01</on_date>
            <start_hour>15:00:00</start_hour>
            <duration_hours>2</duration_hours>
            <location location_id="1">
              <address>
                <street>Nekoja ulica</street>
                <number>11</number>
                <zip>8000</zip>
                <city>Grad</city>
                <country>Drzava</country>
              </address>
              <capacity>20</capacity>
              <lesson_type>
                <online>
                  <platform>Zoom</platform>
                </online>
              </lesson_type>
            </location>
            <lecturer_teach_lecture ssn_lecturer="1234567890000"/>
          </lecture>
        </lectures>
      </schedule>
    </schedules>
  </education_center>
</education_centers>
